core/blog/api/V1/urls.py
from django.urls import path , include
from . import views
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView

app_name = "api_V1"

urlpatterns = [
    # path("post/", views.PostList ,name="Post-list"), 
    path("post/", views.PostList.as_view() ,name="Post-list"), 
    # path("post/<int:id>/", views.PostDetail ,name="Post-list"),
    path("post/<int:pk>/", views.PostDetail.as_view(),name="Post-detail"),
]

core/blog/urls.py
from django.urls import path , include
from . import views
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView

app_name = "blog"

urlpatterns = [
    # path("fbv_index" , views.indexView,name='fbv_index'),
    # path("cbv_index", TemplateView.as_view(template_name="index.html",)),
    # path("cbv_index" , views.HomePageView.as_view(),name='cbv_index'),
    path("post/", views.PostList.as_view(), name="Post-list"),
    # path("go-to-LinkedIn/" , views.RedirectToLinkedIn.as_view(),name='redirect to LinkedIn Page'),
    path("post/<int:pk>", views.PostDetailView.as_view(),name='post_detail'),
    path("post/create/", views.PostCreateView.as_view(),name='post_create'),
    path("post/<int:pk>/edit/",  views.PostEditView.as_view(),name = 'post_edit'),
    path("post/<int:pk>/delete/", views.PostDeleteView.as_view(),name = 'post_delete'),
    path('api/V1/', include('blog.api.V1.urls'))
    
]

core/core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('accounts/', include('django.contrib.auth.urls')),  
    path('blog/', include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model
# Create your models here.
User = get_user_model()
class Category(models.Model):
    num = models.CharField(max_length=250)
    def __str__(self):
        return self.num
        
class Post(models.Model):
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    image = models.ImageField(null=True,blank=True)
    title = models.CharField(max_length=250)
    content=  models.TextField()
    status = models.BooleanField()
    category = models.ForeignKey(Category,on_delete=models.SET_NULL,null=True)

    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    published_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

core/blog/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [ 'title' , 'content', 'status', 'category','published_date']

core/blog/api/V1/views.py
from rest_framework.decorators import api_view,permission_classes
from rest_framework.permissions import IsAuthenticatedOrReadOnly,IsAdminUser,IsAuthenticated
from rest_framework.response import Response
from .serializers import PostSerializer
from blog.models import Post
from rest_framework import status
from django.shortcuts import get_object_or_404
from rest_framework.views import APIView
from rest_framework import authentication, permissions
from rest_framework.generics import CreateAPIView , ListAPIView  , RetrieveAPIView ,GenericAPIView , ListCreateAPIView ,RetrieveUpdateAPIView , RetrieveUpdateDestroyAPIView
from rest_framework import mixins


'''fbv for PostList'''
'''
@api_view(["POST","GET"])
@permission_classes([IsAuthenticated])
def PostList(request):
    if request.method =="GET":
        posts = Post.objects.filter(status=True)
        Serializer = PostSerializer(posts,many=True)
        return Response(Serializer.data)
    elif request.method =="POST":
        Serializer = PostSerializer(data = request.data)
        Serializer.is_valid(raise_exception=True)
        Serializer.save()
        return Response (Serializer.data)


'''

'''write with apiView'''
'''
class PostList(APIView):

    permission_classes = [IsAuthenticatedOrReadOnly]
    serializer_class = PostSerializer

    """getting a list of post and creating a new post"""
    def get(self, request):

        """
        Return a list of all users.
        """
        posts = Post.objects.filter(status=True)
        Serializer = PostSerializer(posts,many=True)
        return Response(Serializer.data)
    

    """retrieving a list of post"""
    def post(self, request):

        """
        created a post with provided.
        """

        Serializer = PostSerializer(data = request.data)
        Serializer.is_valid(raise_exception=True)
        Serializer.save()
        return Response (Serializer.data)
    
'''    

'''write with GenericAPIView'''
        
class PostList(ListCreateAPIView):

    permission_classes = [IsAuthenticatedOrReadOnly]
    serializer_class = PostSerializer
    queryset = Post.objects.filter(status=True)




'''fbv for PostDetail'''
'''
@api_view(["PUT","GET","DELETE"])
@permission_classes([IsAuthenticatedOrReadOnly])
def PostDetail(request,id):
    post = get_object_or_404(Post,pk=id,status=True)
    if request.method =="GET":
        Serializer = PostSerializer(post)
        return Response(Serializer.data)
    elif request.method =="PUT":
        Serializer = PostSerializer(post,data=request.data)
        Serializer.is_valid(raise_exception=True)
        Serializer.save()
        return Response (Serializer.data)

    elif request.method =="DELETE":
        post.delete()
        return Response({"detail":"Item removed successfully"},status=status.HTTP_204_NO_CONTENT)
    
'''

'''Write with apiView'''
'''
class PostDetail(APIView):
    permission_classes = [IsAuthenticatedOrReadOnly]
    serializer_class = PostSerializer

    """retrieving the post data"""
    def get(self, request,id):
        post = get_object_or_404(Post,pk=id,status=True)
        Serializer = PostSerializer(post)
        return Response(Serializer.data)
    
    """editing the post data"""
    def put(self, request,id):
        post = get_object_or_404(Post,pk=id,status=True)
        Serializer = PostSerializer(post,data=request.data)
        Serializer.is_valid(raise_exception=True)
        Serializer.save()
        return Response (Serializer.data)
    
    """delete the post"""
    def delete(self, request,id):
        post = get_object_or_404(Post,pk=id,status=True)
        post.delete()
        return Response({"detail":"Item removed successfully"},status=status.HTTP_204_NO_CONTENT)
'''

'''write with GenericAPIView for PostDetail'''

class PostDetail(RetrieveUpdateDestroyAPIView):
    permission_classes = [IsAuthenticatedOrReadOnly]
    serializer_class = PostSerializer
    queryset = Post.objects.filter(status=True)

core/blog/views.py
from django.shortcuts import render  
from django.views.generic.base import TemplateView
from .models import Post
from django.views.generic.base import RedirectView 
from django.views.generic import ListView , DetailView , FormView , CreateView , UpdateView , DeleteView
from .forms import PostForm
from django.contrib.auth.mixins import LoginRequiredMixin , PermissionRequiredMixin
from django.http import HttpResponse

# Create your views here.

# fbv Show a Template

"""
def indexView(request):

    # the function base views to show index page
    
    name = 'ali' 
    posts = Post.objects.all()
    context = {"name": name, "posts": posts}
    return render(request, 'index.html', context)
"""

class HomePageView(TemplateView):

    """
    the class base views to show index page
    """

    template_name = "index.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["name"] = 'ali'
        context["posts"] = Post.objects.all()  # Fetch all posts from the database and add it to the context.  # Assuming Post is a model that represents your blog posts.  # Replace this line with your actual database query.  # This is a simple example to demonstrate the concept.  # In a real-world application, you should fetch the posts based on the user's preferences and other criteria.  # Also, you should paginate the posts to avoid
        return context
    

# fbv for redirect

"""
 def RedirectToLinkedIn(request):

    # the function base views to redirect to another page
    
    return redirect('https://linkedin.com/feed/')
"""

class RedirectToLinkedIn(RedirectView):

    """
    the class base views to redirect to another page
    """

    url = "https://linkedin.com/in/amirabbas-afrasiyabi-a6a230259/"


# cbv for list

class PostList(PermissionRequiredMixin,LoginRequiredMixin,ListView):

    """
    the class base views to show all posts
    """

    permission_required = "blog.view_post"
    # models1
    # queryset = Post.objects.all()

    # models2
    model = Post
    # same for all three models
    template_name = "blog/post_list.html"
    context_object_name = "posts"
    paginate_by = 2  # Set the number of posts to show per page.
    ordering = "-published_date"  # Set the order of posts to be displayed. You can also use "-created_date" or any other field.
    queryset = Post.objects.filter(status=True)  # Filter posts to only show published ones. You can also use "-created_date" or any other field.
    
    #models3
    # def get_queryset(self):
    #     posts = Post.objects.filter(status=True)
    #     return posts

class PostDetailView(DetailView):
    model = Post
    template_name = "blog/post_detail.html"
    context_object_name = "post"

"""
class PostCreateView(FormView):
    template_name = "contact.html"
    form_class = PostForm
    success_url = '/blog/post/'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)
"""

class PostCreateView(CreateView):
    model = Post
    # fields = ['id', 'author', 'title', 'content', 'status', 'category','published_date']
    form_class = PostForm
    success_url = '/blog/post/'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    

class PostEditView(UpdateView):
    model = Post
    form_class = PostForm
    success_url = '/blog/post/'

class PostDeleteView(DeleteView):
    model = Post
    success_url = '/blog/post/'

core/templates/blog/post_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>delete</title>
</head>
<body>
    <form method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        {{ form }}
        <input type="submit" value="Confirm">
    </form>
</body>
</html>

core/templates/blog/post_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>index</title>
</head>
<body>
    <h1>{{object.title}}</h1>
    <hr>
    <small>{{object.author}} - {{object.published_date}}</small>
    <p>{{object.content|linebreaks}}</p>
</body>
</html>

core/templates/blog/post_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>create post</title>
</head>
<body>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Send message">
    </form>
</body>
</html>

core/templates/blog/post_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>index</title>
</head>
<body>
    
    <h2>blog post</h2>
    {% if posts %}
        <ul>
            {% for post in posts %}
                <li>
                    <a href="{% url 'blog:post_detail' pk=post.id %}"><h3>{{post.id}} - {{ post.title }}</h3></a>
                    <a href="{% url 'blog:post_edit' pk=post.id %}">
                        <h5>edit</h5>
                    </a>

                    <a href="{% url 'blog:post_delete' pk=post.id %}">
                        <h5>delete</h5>
                    </a>
                    <small>{{ post.author }} - {{ post.published_date }} </small>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No posts available.</p>
    {% endif %}
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
    
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>

</body>
</html>